apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-kant-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0p0inter/nodejs-kant-app.git
    path: k8s/nodejs-kant-app
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-sample-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true