name: 'Build & Push Docker Image'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  bump:
    uses: 0p0inter/nodejs-kant-app/.github/workflows/push_main_bump.yml@main
  scan: 
    uses: 0p0inter/nodejs-kant-app/.github/workflows/pull_main_scan.yml@main
  docker:
    name: 'Build & Push Docker Image to Docker Hub'
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 0p0inter/nodejs-kant-app:${{ needs.bump.outputs.NEW_TAG }}
      - name: 'Source code checkout'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: Update Helm Chart Values
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: k8s/nodejs-kant-app/values.yaml
          tag_value: ${{ needs.bump.outputs.NEW_TAG }}
          # bump_level: patch
          # helm_docs: true
          commit_branch: main
          commit_tag: ${{ needs.bump.outputs.NEW_TAG }}-chart
          # commit_and_push: true
          # commit_message: Automated commit on behalf-of ${{ github.actor }}
          # commit_options: ''
          # verbose: false
          # dry: false